### ISSUE TITLE
There is a question while installing the master branch

### ISSUE THREAD

**Issue by horcsinbalint** [ioi-2023/contestant-vm#29]
![image](https://github.com/ioi-2023/contestant-vm/assets/51171286/d3236cd4-d88c-49d3-afdc-de84e8aa571e)

**Comment by radl97** [comment]
Ooh, thanks for the heads-up! This is already fixed in published-vm. I'll merge from published-vm all necessary things right away!

There might be similar -- already solved -- issues like this on master. E.g. network access. Please wait a bit for me to sync branches (if I close this issue, then it means all related problems are solved)

**Comment by horcsinbalint** [comment]
Okay, I just mistakenly started the build process from master and came across this

**Comment by radl97** [comment]
Thanks for documenting it. I would not have caught it.
