### ISSUE TITLE
Issues with Eclipse on Wayland and X11

### ISSUE THREAD

**Issue by horcsinbalint** [ioi-2023/contestant-vm#42]
It's probably only an issue on my machine. When I use VMWare, the text cursor is vibrating. Even if I give it plenty of resources. https://youtu.be/2V-0aRnd-1A
On QEMU, there isn't such issue.
On the competition, contestants will use natively installed Linux, right? @niklaci @radl97 If yes, I think it doesn't need to be fixed.

**Comment by radl97** [comment]
Yes. Thanks for the thorough testing!

I think we can close this issue then.

**Comment by horcsinbalint** [comment]
Changing to:
```
cat - <<EOM > /usr/share/applications/eclipse.desktop
[Desktop Entry]
Name=Eclipse
Exec=env GDK_BACKEND=x11 /opt/eclipse/eclipse
Type=Application
Icon=eclipse
EOM
```
Can probably fix the issue. `xeyes` shows the prior to that not xwayland was used. I will test this idea.

**Comment by horcsinbalint** [comment]
It has introduced a weird bug:
If you create a project, some keys will not work (arrows, return, backspace, etc.) in eclipse. But if you remove focus from the window, and then focus on it, it will start working.

**Comment by radl97** [comment]
A) and B) are a nogo.

Ubuntu migration was done, and enough tests were done to ensure that everything would be okay. Both the server and contestant systems were updated, to enable contestants use latest g++ versions (only ~3 year old?, when the Debian version freeze happened on which Ubuntu started out from.) The contestant laptop was updated in order to ensure the compatibility of the toolchains with the evaluation system.

Also, we have asked contestants to check their favourite tools and report problems. No contestant has indicated experiencing such issue -- probably not too many people are relying on Eclipse.

**Comment by horcsinbalint** [comment]
I have made the changes on https://github.com/ioi-2023/contestant-vm/compare/master...horcsinbalint:contestant-vm:eclipse-xwayland
