### ISSUE TITLE
vscodevim isn't actually installed

### ISSUE THREAD

**Issue by baltitenger** [ioi-2023/contestant-vm#58]

**Comment by radl97** [comment]
It is downloaded, and importing it from GUI works. However, after installing, it *enables* the VIM extension, making life harder for everyone not wanting to use vim.

I think the best behavior we can come up with is installing *and disabling* vim. Summarized in a picture:

![image](https://github.com/ioi-2023/contestant-vm/assets/7879888/8ad1cddb-c67d-4a44-b5ff-180d01d7aff7)

During investigation, I have found:

- This line is useless: https://github.com/ioi-2023/contestant-vm/blob/a262ca0590a3f27d72652c57b4ba8d56cf9632a0/setup.sh#L127
- [Packed version of the extensions](https://github.com/ioi-2023/contestant-vm/blob/a262ca0590a3f27d72652c57b4ba8d56cf9632a0/setup.sh#L126) are used [in mkioiuser.sh](https://github.com/ioi-2023/contestant-vm/blob/a262ca0590a3f27d72652c57b4ba8d56cf9632a0/sbin/mkioiuser.sh#L55). This is probably the code which successfully installs VSCode for the `ioi` user.
- [This](https://github.com/ioi-2023/contestant-vm/blob/a262ca0590a3f27d72652c57b4ba8d56cf9632a0/setup.sh#L125) code also seems useless (it seems it installs the extension for `ansible`)

**Comment by radl97** [comment]
> HSC last year [...] said that it was impossible to have an extension installed in VSCode but disabled by default programmatically (they linked [this](https://github.com/microsoft/vscode/issues/40239) and [this](https://github.com/microsoft/vscode/issues/52639)).

So we cannot disable-by-default too easily. I think we can do one of two things.

- Install different desktop icons which start VSCode with set of different extensions. This is problematic, because if `code` is started from the terminal, it will be a surprising behavior (all extensions will be enabled). 
- Document how to install VSCode vim mode in the manual, if they want to use it. (Open VSCode, File -> Import VSIX -> `/opt/ioi/misc/vscodevim.vsix`) This has to be done at the beginning of each contest day, because the contestant site's state is reset.

This goes also for #60 .

**Comment by baltitenger** [comment]
Yeah, I forgot to mention that I did some research too, and it seems that the disabled state of extensions is stored in an sqlite db. I gues it might be possible to do programmatically but slightly painful.
